// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OM.MFPTracker.Data;

#nullable disable

namespace OM.MFPTracker.Data.Migrations
{
    [DbContext(typeof(MFPTrackerDbContext))]
    [Migration("20260206093137_MFdataadded")]
    partial class MFdataadded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("OM.MFPTracker.Data.Models.Dummy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateTime>("InDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("updateDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("DummyTable", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "DK",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "RS",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("OM.MFPTracker.Data.Models.MFCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("TMFCategory", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "E-Multi Cap Mutual Funds"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "E-Flexi Cap Mutual Funds"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "E-Large & MidCap Mutual Funds"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "E-Large Cap Mutual Funds"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "E-Mid Cap Mutual Funds"
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "E-ELSS Mutual Funds"
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "E-Dividend Yield Mutual Funds"
                        },
                        new
                        {
                            Id = 8,
                            CategoryName = "E-Contra Mutual Funds"
                        },
                        new
                        {
                            Id = 9,
                            CategoryName = "E-Sectoral Mutual Funds"
                        },
                        new
                        {
                            Id = 10,
                            CategoryName = "E-Value Oriented Mutual Funds"
                        });
                });

            modelBuilder.Entity("OM.MFPTracker.Data.Models.MutualFund", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ISIN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateTime>("InDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("MFCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SchemeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("SchemeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ISIN")
                        .IsUnique();

                    b.HasIndex("MFCategoryId");

                    b.HasIndex("SchemeCode")
                        .IsUnique();

                    b.ToTable("TMutualFunds", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ISIN = "123AA",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MFCategoryId = 2,
                            SchemeCode = "B2C67",
                            SchemeName = "DK MF"
                        },
                        new
                        {
                            Id = 2,
                            ISIN = "12B4C",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MFCategoryId = 1,
                            SchemeCode = "AAC27",
                            SchemeName = "RK MF"
                        },
                        new
                        {
                            Id = 3,
                            ISIN = "INF879O01027",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MFCategoryId = 1,
                            SchemeCode = "122639",
                            SchemeName = "Parag Parikh Flexi Cap Fund - Direct Plan - Growth"
                        },
                        new
                        {
                            Id = 4,
                            ISIN = "INF760K01167",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MFCategoryId = 2,
                            SchemeCode = "102920",
                            SchemeName = "CANARA ROBECO LARGE AND MID CAP FUND - REGULAR PLAN - GROWTH"
                        });
                });

            modelBuilder.Entity("OM.MFPTracker.Data.Models.NavHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("InDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("MutualFundId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NavDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NavValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MutualFundId", "NavDate")
                        .IsUnique();

                    b.ToTable("TNavHistory", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MutualFundId = 1,
                            NavDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NavValue = 125.4321m
                        },
                        new
                        {
                            Id = 2,
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MutualFundId = 1,
                            NavDate = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NavValue = 126.1000m
                        },
                        new
                        {
                            Id = 3,
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MutualFundId = 2,
                            NavDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NavValue = 98.7500m
                        },
                        new
                        {
                            Id = 4,
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MutualFundId = 2,
                            NavDate = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NavValue = 99.2500m
                        });
                });

            modelBuilder.Entity("OM.MFPTracker.Data.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("People", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(2002, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Rupam",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Shaw",
                            Signature = "RS",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1981, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Deepak",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Shaw",
                            Signature = "DK",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1974, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jagruti",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Shaw",
                            Signature = "JS",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(2001, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Divyam",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Shaw",
                            Signature = "DS",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Durga Prasad",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Shaw",
                            Signature = "DP",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Radha",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Shaw",
                            Signature = "RD",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("OM.MFPTracker.Data.Models.SpecialEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventDate");

                    b.ToTable("TSpecialEvents", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventDate = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "GlobalMacro",
                            Notes = "High inflation, pressure on Indian equities and rupee due to elevated energy prices",
                            Title = "Global Energy Crisis & Commodity Price Shock"
                        },
                        new
                        {
                            Id = 2,
                            EventDate = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Climate",
                            Notes = "Concerns over food inflation and rural demand in India",
                            Title = "El Niño Impact on Global Agriculture"
                        },
                        new
                        {
                            Id = 3,
                            EventDate = new DateTime(2023, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Corporate",
                            Notes = "Sharp selloff in Adani stocks, dragged broader Indian indices",
                            Title = "Adani Group Short Seller Report Fallout"
                        },
                        new
                        {
                            Id = 4,
                            EventDate = new DateTime(2023, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Regulatory",
                            Notes = "Structural reform improving liquidity and settlement efficiency",
                            Title = "India Implements T+1 Settlement"
                        },
                        new
                        {
                            Id = 5,
                            EventDate = new DateTime(2024, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Elections",
                            Notes = "High volatility in Sensex and Nifty based on election outcome",
                            Title = "India General Election Results 2024"
                        },
                        new
                        {
                            Id = 6,
                            EventDate = new DateTime(2024, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "MarketMilestone",
                            Notes = "Positive sentiment and global visibility for Indian equities",
                            Title = "India Becomes World's 4th Largest Stock Market"
                        },
                        new
                        {
                            Id = 7,
                            EventDate = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "MonetaryPolicy",
                            Notes = "Impacted FII flows and emerging market valuations including India",
                            Title = "US Federal Reserve Rate Outlook Shift"
                        },
                        new
                        {
                            Id = 8,
                            EventDate = new DateTime(2024, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Geopolitics",
                            Notes = "Global risk-off sentiment affecting export-oriented Indian stocks",
                            Title = "US-China Trade & Tech Tensions Escalate"
                        },
                        new
                        {
                            Id = 9,
                            EventDate = new DateTime(2025, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "GlobalMacro",
                            Notes = "Sharp correction across global equities including Indian markets",
                            Title = "Global Stock Market Selloff 2025"
                        },
                        new
                        {
                            Id = 10,
                            EventDate = new DateTime(2025, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "TradePolicy",
                            Notes = "Negative impact on rupee and export-focused Indian stocks",
                            Title = "US Imposes 50% Tariff on Indian Goods"
                        },
                        new
                        {
                            Id = 11,
                            EventDate = new DateTime(2025, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Geopolitics",
                            Notes = "Oil price spike led to inflation concerns in India",
                            Title = "Middle East Conflict Escalation (Israel–Iran)"
                        },
                        new
                        {
                            Id = 12,
                            EventDate = new DateTime(2025, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "GlobalMacro",
                            Notes = "Spillover risk aversion affecting emerging markets including India",
                            Title = "Turkey Currency Crisis & EM Selloff"
                        },
                        new
                        {
                            Id = 13,
                            EventDate = new DateTime(2025, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Geopolitics",
                            Notes = "Short-term volatility in Indian indices and defence stocks",
                            Title = "India-Pakistan Border Tensions (Pahalgam Incident)"
                        },
                        new
                        {
                            Id = 14,
                            EventDate = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "MarketCorrection",
                            Notes = "FII outflows and global risk aversion caused broad market decline",
                            Title = "Indian Market Correction Early 2025"
                        },
                        new
                        {
                            Id = 15,
                            EventDate = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "MonetaryPolicy",
                            Notes = "Pressure on valuations and capital flows to India",
                            Title = "US Fed Signals Prolonged Higher Rates"
                        },
                        new
                        {
                            Id = 16,
                            EventDate = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "EconomicData",
                            Notes = "Boosted confidence in Indian equities and domestic sectors",
                            Title = "India GDP Growth Beats Expectations"
                        },
                        new
                        {
                            Id = 17,
                            EventDate = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "TradePolicy",
                            Notes = "Positive rally in Indian markets and strengthening of rupee",
                            Title = "India-US Trade Deal Announcement"
                        },
                        new
                        {
                            Id = 18,
                            EventDate = new DateTime(2026, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Technology",
                            Notes = "Valuation reset in IT and tech stocks including Indian IT sector",
                            Title = "Global AI & Tech Stock Selloff"
                        },
                        new
                        {
                            Id = 19,
                            EventDate = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Geopolitics",
                            Notes = "Energy and fertilizer price volatility affecting Indian inflation",
                            Title = "Russia-Ukraine War Commodity Impact"
                        },
                        new
                        {
                            Id = 20,
                            EventDate = new DateTime(2024, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "GlobalMacro",
                            Notes = "Increased volatility and cautious FII positioning in Indian markets",
                            Title = "Global Elections & Policy Uncertainty (US/EU)"
                        });
                });

            modelBuilder.Entity("OM.MFPTracker.Data.Models.MutualFund", b =>
                {
                    b.HasOne("OM.MFPTracker.Data.Models.MFCategory", "MFCategory")
                        .WithMany("MutualFunds")
                        .HasForeignKey("MFCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MFCategory");
                });

            modelBuilder.Entity("OM.MFPTracker.Data.Models.NavHistory", b =>
                {
                    b.HasOne("OM.MFPTracker.Data.Models.MutualFund", "MutualFund")
                        .WithMany("NavHistories")
                        .HasForeignKey("MutualFundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MutualFund");
                });

            modelBuilder.Entity("OM.MFPTracker.Data.Models.MFCategory", b =>
                {
                    b.Navigation("MutualFunds");
                });

            modelBuilder.Entity("OM.MFPTracker.Data.Models.MutualFund", b =>
                {
                    b.Navigation("NavHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
