// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OM.MFPTracker.Data;

#nullable disable

namespace OM.MFPTracker.Data.Migrations
{
    [DbContext(typeof(MFPTrackerDbContext))]
    [Migration("20260303120949_MFTransecationAdd")]
    partial class MFTransecationAdd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("OM.MFPTracker.Data.Models.Amc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TAMC", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "HDFC",
                            Name = "HDFC Asset Management Company"
                        },
                        new
                        {
                            Id = 2,
                            Code = "ICICI",
                            Name = "ICICI Prudential Asset Management"
                        },
                        new
                        {
                            Id = 3,
                            Code = "SBI",
                            Name = "SBI Funds Management"
                        },
                        new
                        {
                            Id = 4,
                            Code = "AXIS",
                            Name = "Axis Asset Management"
                        },
                        new
                        {
                            Id = 5,
                            Code = "KOTAK",
                            Name = "Kotak Mahindra Asset Management"
                        },
                        new
                        {
                            Id = 6,
                            Code = "PPFAS",
                            Name = "PPFAS Mutual Fund"
                        },
                        new
                        {
                            Id = 7,
                            Code = "MAMF",
                            Name = "Mirae Asset Mutual Fund"
                        },
                        new
                        {
                            Id = 8,
                            Code = "CRAMC",
                            Name = "CANARA ROBECO Mutual Fund"
                        },
                        new
                        {
                            Id = 9,
                            Code = "BANDHAN MF",
                            Name = "BANDHAN Mutual Fund"
                        },
                        new
                        {
                            Id = 10,
                            Code = "NIMF",
                            Name = "Nippon India Mutual Fund"
                        },
                        new
                        {
                            Id = 11,
                            Code = "TMF",
                            Name = "Tata Asset Management"
                        });
                });

            modelBuilder.Entity("OM.MFPTracker.Data.Models.Dummy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateTime>("InDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("updateDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("DummyTable", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "DK",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "RS",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("OM.MFPTracker.Data.Models.Folio", b =>
                {
                    b.Property<int>("FolioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AmcId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttachedBank")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FolioDescription")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("FolioHolderId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FolioIsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FolioName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("FolioPurpose")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("FolioId");

                    b.HasIndex("AmcId");

                    b.HasIndex("FolioHolderId");

                    b.HasIndex("FolioName")
                        .IsUnique();

                    b.ToTable("TFolio", (string)null);

                    b.HasData(
                        new
                        {
                            FolioId = 1,
                            AmcId = 1,
                            AttachedBank = "HDFC Bank",
                            FolioDescription = "Primary Investment Folio",
                            FolioHolderId = 1,
                            FolioIsActive = true,
                            FolioName = "HDFC-001",
                            FolioPurpose = "Long term wealth creation",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FolioId = 2,
                            AmcId = 1,
                            AttachedBank = "KOTAK NRE Bank",
                            FolioDescription = "Canara Rebeko Investment Folio",
                            FolioHolderId = 1,
                            FolioIsActive = true,
                            FolioName = "CANREB-001",
                            FolioPurpose = "Long term wealth creation",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("OM.MFPTracker.Data.Models.FolioHolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("TFolioHolder", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(2002, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Rupam",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Shaw",
                            Signature = "RS",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1981, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Deepak",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Shaw",
                            Signature = "DK",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1974, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jagruti",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Shaw",
                            Signature = "JS",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(2001, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Divyam",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Shaw",
                            Signature = "DS",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Durga Prasad",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Shaw",
                            Signature = "DP",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Radha",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Shaw",
                            Signature = "RD",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("OM.MFPTracker.Data.Models.FundTransaction", b =>
                {
                    b.Property<int>("FundTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Charges")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ConsumedBuyTransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FolioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FundId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("InDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("Nav")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SellGroupId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Units")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("UnitsLeft")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("FundTransactionId");

                    b.HasIndex("ConsumedBuyTransactionId");

                    b.HasIndex("FolioId");

                    b.HasIndex("FundId");

                    b.HasIndex("SellGroupId");

                    b.HasIndex("TransactionDate");

                    b.HasIndex("Type");

                    b.HasIndex("FolioId", "FundId", "TransactionDate");

                    b.ToTable("TFundTransaction", (string)null);

                    b.HasData(
                        new
                        {
                            FundTransactionId = 1,
                            Amount = 12050.00m,
                            Charges = 10.50m,
                            FolioId = 1,
                            FundId = 1,
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nav = 120.50m,
                            Remarks = "Initial purchase",
                            TransactionDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Units = 100.000000m,
                            UnitsLeft = 60.000000m,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FundTransactionId = 2,
                            Amount = 6030.00m,
                            Charges = 5.25m,
                            ConsumedBuyTransactionId = 1,
                            FolioId = 1,
                            FundId = 1,
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nav = 150.75m,
                            Remarks = "Partial profit booking",
                            SellGroupId = new Guid("3e9f2c0d-5e0a-4f1c-9f8b-9c9b3b7f0a11"),
                            TransactionDate = new DateTime(2024, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 2,
                            Units = 40.000000m,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FundTransactionId = 3,
                            Amount = 1050.00m,
                            Charges = 1.25m,
                            FolioId = 2,
                            FundId = 2,
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nav = 10.500000m,
                            Remarks = "more mf bought Investment",
                            TransactionDate = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Units = 100.000000m,
                            UnitsLeft = 60.000000m,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FundTransactionId = 4,
                            Amount = 480.00m,
                            Charges = 5.00m,
                            ConsumedBuyTransactionId = 3,
                            FolioId = 1,
                            FundId = 1,
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nav = 12.000000m,
                            Remarks = "Partial Profit Booking",
                            SellGroupId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TransactionDate = new DateTime(2024, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 2,
                            Units = 40.000000m,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("OM.MFPTracker.Data.Models.MFCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("TMFCategory", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "E-Multi Cap Mutual Funds"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "E-Flexi Cap Mutual Funds"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "E-Large & MidCap Mutual Funds"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "E-Large Cap Mutual Funds"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "E-Mid Cap Mutual Funds"
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "E-ELSS Mutual Funds"
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "E-Dividend Yield Mutual Funds"
                        },
                        new
                        {
                            Id = 8,
                            CategoryName = "E-Contra Mutual Funds"
                        },
                        new
                        {
                            Id = 9,
                            CategoryName = "E-Sectoral Mutual Funds"
                        },
                        new
                        {
                            Id = 10,
                            CategoryName = "E-Value Oriented Mutual Funds"
                        });
                });

            modelBuilder.Entity("OM.MFPTracker.Data.Models.MutualFund", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmcId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ISIN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateTime>("InDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("MFCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OperationalStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SchemeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("SchemeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AmcId");

                    b.HasIndex("ISIN")
                        .IsUnique();

                    b.HasIndex("MFCategoryId");

                    b.HasIndex("OperationalStatusId");

                    b.HasIndex("SchemeCode")
                        .IsUnique();

                    b.ToTable("TMutualFunds", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmcId = 4,
                            ISIN = "INF846K01K35",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MFCategoryId = 2,
                            OperationalStatusId = 1,
                            SchemeCode = "125354",
                            SchemeName = "AXIS SMALL CAP Fund - DIRECT PLAN - GROWTH"
                        },
                        new
                        {
                            Id = 2,
                            AmcId = 9,
                            ISIN = "INF194KB1AJ8",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MFCategoryId = 2,
                            OperationalStatusId = 1,
                            SchemeCode = "147944",
                            SchemeName = "BANDHAN SMALL CAP FUND - REGULAR PLAN GROWTH"
                        },
                        new
                        {
                            Id = 3,
                            AmcId = 8,
                            ISIN = "INF760K01167",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MFCategoryId = 2,
                            OperationalStatusId = 1,
                            SchemeCode = "102920",
                            SchemeName = "CANARA ROBECO LARGE AND MID CAP FUND - REGULAR PLAN - GROWTH"
                        },
                        new
                        {
                            Id = 4,
                            AmcId = 8,
                            ISIN = "INF760K01EI4",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MFCategoryId = 2,
                            OperationalStatusId = 1,
                            SchemeCode = "118278",
                            SchemeName = "CANARA ROBECO LARGE AND MID CAP FUND - DIRECT PLAN - GROWTH"
                        },
                        new
                        {
                            Id = 5,
                            AmcId = 8,
                            ISIN = "INF760K01JC6",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MFCategoryId = 2,
                            OperationalStatusId = 1,
                            SchemeCode = "146130",
                            SchemeName = "CANARA ROBECO SMALL CAP FUND - DIRECT PLAN - GROWTH"
                        },
                        new
                        {
                            Id = 6,
                            AmcId = 8,
                            ISIN = "INF760K01JW4",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MFCategoryId = 2,
                            OperationalStatusId = 1,
                            SchemeCode = "149085",
                            SchemeName = "CANARA ROBECO VALUE FUND - DIRECT PLAN - GROWTH"
                        },
                        new
                        {
                            Id = 7,
                            AmcId = 5,
                            ISIN = "INF174K01LS2",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MFCategoryId = 2,
                            OperationalStatusId = 1,
                            SchemeCode = "120166",
                            SchemeName = "KOTAK FLEXICAP FUND - DIRECT PLAN - GROWTH"
                        },
                        new
                        {
                            Id = 8,
                            AmcId = 5,
                            ISIN = "INF174K01LF9",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MFCategoryId = 2,
                            OperationalStatusId = 1,
                            SchemeCode = "120158",
                            SchemeName = "KOTAK LARGE & MIDCAP FUND - DIRECT PLAN - GROWTH"
                        },
                        new
                        {
                            Id = 9,
                            AmcId = 7,
                            ISIN = "INF769K01BI1",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MFCategoryId = 2,
                            OperationalStatusId = 1,
                            SchemeCode = "118834",
                            SchemeName = "MIRAE ASSET LARGE & MIDCAP FUND - DIRECT PLAN - GROWTH"
                        },
                        new
                        {
                            Id = 10,
                            AmcId = 7,
                            ISIN = "INF769K01HP3",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MFCategoryId = 2,
                            OperationalStatusId = 1,
                            SchemeCode = "149169",
                            SchemeName = "MIRAE ASSET S&P 500 Top 50 ETF"
                        },
                        new
                        {
                            Id = 11,
                            AmcId = 7,
                            ISIN = "INF769K01HF4",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MFCategoryId = 2,
                            OperationalStatusId = 1,
                            SchemeCode = "148927",
                            SchemeName = "MIRAE ASSET NYSE FANG + ETF"
                        },
                        new
                        {
                            Id = 12,
                            AmcId = 7,
                            ISIN = "INF769K01DM9",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MFCategoryId = 2,
                            OperationalStatusId = 1,
                            SchemeCode = "135781",
                            SchemeName = "MIRAE ASSET ELSS Tax Saver FUND - DIRECT PLAN - GROWTH"
                        },
                        new
                        {
                            Id = 13,
                            AmcId = 10,
                            ISIN = "INF204K01K15",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MFCategoryId = 2,
                            OperationalStatusId = 1,
                            SchemeCode = "118778",
                            SchemeName = "NIPPON INDIA SMALL CAP FUND - Direct Plan Growth Plan - Growth Option"
                        },
                        new
                        {
                            Id = 14,
                            AmcId = 6,
                            ISIN = "INF879O01266",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MFCategoryId = 2,
                            OperationalStatusId = 1,
                            SchemeCode = "152468",
                            SchemeName = "PARAG PARIKH DYNAMIC ASSET ALLOCATION FUND - DIRECT PLAN - GROWTH"
                        },
                        new
                        {
                            Id = 15,
                            AmcId = 6,
                            ISIN = "INF879O01027",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MFCategoryId = 1,
                            OperationalStatusId = 1,
                            SchemeCode = "122639",
                            SchemeName = "PARAG PARIKH FLEXI CAP FUND- DIRECT PLAN - GROWTH"
                        },
                        new
                        {
                            Id = 16,
                            AmcId = 3,
                            ISIN = "INF200K01QX4",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MFCategoryId = 2,
                            OperationalStatusId = 1,
                            SchemeCode = "119598",
                            SchemeName = "SBI LARGE Cap FUND - DIRECT PLAN - GROWTH"
                        },
                        new
                        {
                            Id = 17,
                            AmcId = 3,
                            ISIN = "INF200K01T51",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MFCategoryId = 2,
                            OperationalStatusId = 1,
                            SchemeCode = "125497",
                            SchemeName = "SBI SMALL Cap FUND - DIRECT PLAN - GROWTH"
                        },
                        new
                        {
                            Id = 18,
                            AmcId = 11,
                            ISIN = "INF277K01QO1",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MFCategoryId = 2,
                            OperationalStatusId = 1,
                            SchemeCode = "119251",
                            SchemeName = "TATA RETIREMENT SAVINGS FUND - PROGRESSIVE Plan - DIRECT PLAN - GROWTH"
                        },
                        new
                        {
                            Id = 19,
                            AmcId = 11,
                            ISIN = "INF277K01PK1",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MFCategoryId = 2,
                            OperationalStatusId = 1,
                            SchemeCode = "119287",
                            SchemeName = "TATA S&P BSE SENSEX Index FUND - DIRECT PLAN"
                        },
                        new
                        {
                            Id = 20,
                            AmcId = 11,
                            ISIN = "x",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MFCategoryId = 2,
                            OperationalStatusId = 2,
                            SchemeCode = "0",
                            SchemeName = "TEST ME FUND - DIRECT PLAN"
                        });
                });

            modelBuilder.Entity("OM.MFPTracker.Data.Models.MutualFundTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("FundCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("FundName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FundType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NAV")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Units")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("Folio");

                    b.HasIndex("FundName", "FundCode");

                    b.HasIndex("Folio", "FundName", "Date");

                    b.ToTable("TMutualFundTransaction", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountPaid = 480.000000000000m,
                            CreatedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Folio = "DK001",
                            FundCode = "HDF003",
                            FundName = "HDFC Small cap",
                            FundType = "GR - Multi Cap",
                            NAV = 12.000000m,
                            Note = "data seeding",
                            Source = "Kotak M Bank",
                            Units = 40.000000m,
                            UpdatedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AmountPaid = 350.000000000000m,
                            CreatedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2025, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Folio = "DK001",
                            FundCode = "HDF003",
                            FundName = "HDFC Flexi cap",
                            FundType = "GR - flexi Cap",
                            NAV = 2.500000m,
                            Note = "data seeding",
                            Source = "Kotak M Bank",
                            Units = 140.000000m,
                            UpdatedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("OM.MFPTracker.Data.Models.NavHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("InDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("MutualFundId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NavDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NavValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MutualFundId", "NavDate")
                        .IsUnique();

                    b.ToTable("TNavHistory", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MutualFundId = 1,
                            NavDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NavValue = 125.4321m
                        },
                        new
                        {
                            Id = 2,
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MutualFundId = 1,
                            NavDate = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NavValue = 126.1000m
                        });
                });

            modelBuilder.Entity("OM.MFPTracker.Data.Models.OperationalStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsNavAllowed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTransactionAllowed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TOperationalStatus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ACTIVE",
                            Description = "Open to new investors with continuous subscriptions and redemption",
                            IsNavAllowed = true,
                            IsTransactionAllowed = true
                        },
                        new
                        {
                            Id = 2,
                            Code = "CLOSED",
                            Description = "Units available only during NFO with fixed maturity",
                            IsNavAllowed = false,
                            IsTransactionAllowed = false
                        },
                        new
                        {
                            Id = 3,
                            Code = "SUSPENDED",
                            Description = "Temporarily halted due to regulatory or market conditions",
                            IsNavAllowed = false,
                            IsTransactionAllowed = false
                        },
                        new
                        {
                            Id = 4,
                            Code = "CLOSED_NEW",
                            Description = "Not accepting new investments",
                            IsNavAllowed = false,
                            IsTransactionAllowed = false
                        },
                        new
                        {
                            Id = 5,
                            Code = "LIQUIDATED",
                            Description = "Fund closed and assets paid out or merged",
                            IsNavAllowed = false,
                            IsTransactionAllowed = false
                        });
                });

            modelBuilder.Entity("OM.MFPTracker.Data.Models.SpecialEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventDate");

                    b.ToTable("TSpecialEvents", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventDate = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "GlobalMacro",
                            Notes = "High inflation, pressure on Indian equities and rupee due to elevated energy prices",
                            Title = "Global Energy Crisis & Commodity Price Shock"
                        },
                        new
                        {
                            Id = 2,
                            EventDate = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Climate",
                            Notes = "Concerns over food inflation and rural demand in India",
                            Title = "El Niño Impact on Global Agriculture"
                        },
                        new
                        {
                            Id = 3,
                            EventDate = new DateTime(2023, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Corporate",
                            Notes = "Sharp selloff in Adani stocks, dragged broader Indian indices",
                            Title = "Adani Group Short Seller Report Fallout"
                        },
                        new
                        {
                            Id = 4,
                            EventDate = new DateTime(2023, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Regulatory",
                            Notes = "Structural reform improving liquidity and settlement efficiency",
                            Title = "India Implements T+1 Settlement"
                        },
                        new
                        {
                            Id = 5,
                            EventDate = new DateTime(2024, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Elections",
                            Notes = "High volatility in Sensex and Nifty based on election outcome",
                            Title = "India General Election Results 2024"
                        },
                        new
                        {
                            Id = 6,
                            EventDate = new DateTime(2024, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "MarketMilestone",
                            Notes = "Positive sentiment and global visibility for Indian equities",
                            Title = "India Becomes World's 4th Largest Stock Market"
                        },
                        new
                        {
                            Id = 7,
                            EventDate = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "MonetaryPolicy",
                            Notes = "Impacted FII flows and emerging market valuations including India",
                            Title = "US Federal Reserve Rate Outlook Shift"
                        },
                        new
                        {
                            Id = 8,
                            EventDate = new DateTime(2024, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Geopolitics",
                            Notes = "Global risk-off sentiment affecting export-oriented Indian stocks",
                            Title = "US-China Trade & Tech Tensions Escalate"
                        },
                        new
                        {
                            Id = 9,
                            EventDate = new DateTime(2025, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "GlobalMacro",
                            Notes = "Sharp correction across global equities including Indian markets",
                            Title = "Global Stock Market Selloff 2025"
                        },
                        new
                        {
                            Id = 10,
                            EventDate = new DateTime(2025, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "TradePolicy",
                            Notes = "Negative impact on rupee and export-focused Indian stocks",
                            Title = "US Imposes 50% Tariff on Indian Goods"
                        },
                        new
                        {
                            Id = 11,
                            EventDate = new DateTime(2025, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Geopolitics",
                            Notes = "Oil price spike led to inflation concerns in India",
                            Title = "Middle East Conflict Escalation (Israel–Iran)"
                        },
                        new
                        {
                            Id = 12,
                            EventDate = new DateTime(2025, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "GlobalMacro",
                            Notes = "Spillover risk aversion affecting emerging markets including India",
                            Title = "Turkey Currency Crisis & EM Selloff"
                        },
                        new
                        {
                            Id = 13,
                            EventDate = new DateTime(2025, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Geopolitics",
                            Notes = "Short-term volatility in Indian indices and defence stocks",
                            Title = "India-Pakistan Border Tensions (Pahalgam Incident)"
                        },
                        new
                        {
                            Id = 14,
                            EventDate = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "MarketCorrection",
                            Notes = "FII outflows and global risk aversion caused broad market decline",
                            Title = "Indian Market Correction Early 2025"
                        },
                        new
                        {
                            Id = 15,
                            EventDate = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "MonetaryPolicy",
                            Notes = "Pressure on valuations and capital flows to India",
                            Title = "US Fed Signals Prolonged Higher Rates"
                        },
                        new
                        {
                            Id = 16,
                            EventDate = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "EconomicData",
                            Notes = "Boosted confidence in Indian equities and domestic sectors",
                            Title = "India GDP Growth Beats Expectations"
                        },
                        new
                        {
                            Id = 17,
                            EventDate = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "TradePolicy",
                            Notes = "Positive rally in Indian markets and strengthening of rupee",
                            Title = "India-US Trade Deal Announcement"
                        },
                        new
                        {
                            Id = 18,
                            EventDate = new DateTime(2026, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Technology",
                            Notes = "Valuation reset in IT and tech stocks including Indian IT sector",
                            Title = "Global AI & Tech Stock Selloff"
                        },
                        new
                        {
                            Id = 19,
                            EventDate = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Geopolitics",
                            Notes = "Energy and fertilizer price volatility affecting Indian inflation",
                            Title = "Russia-Ukraine War Commodity Impact"
                        },
                        new
                        {
                            Id = 20,
                            EventDate = new DateTime(2024, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "GlobalMacro",
                            Notes = "Increased volatility and cautious FII positioning in Indian markets",
                            Title = "Global Elections & Policy Uncertainty (US/EU)"
                        });
                });

            modelBuilder.Entity("OM.MFPTracker.Data.Models.Folio", b =>
                {
                    b.HasOne("OM.MFPTracker.Data.Models.Amc", "Amc")
                        .WithMany("Folios")
                        .HasForeignKey("AmcId");

                    b.HasOne("OM.MFPTracker.Data.Models.FolioHolder", "FolioHolder")
                        .WithMany("Folios")
                        .HasForeignKey("FolioHolderId");

                    b.Navigation("Amc");

                    b.Navigation("FolioHolder");
                });

            modelBuilder.Entity("OM.MFPTracker.Data.Models.FundTransaction", b =>
                {
                    b.HasOne("OM.MFPTracker.Data.Models.FundTransaction", null)
                        .WithMany()
                        .HasForeignKey("ConsumedBuyTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OM.MFPTracker.Data.Models.Folio", "Folio")
                        .WithMany("Transactions")
                        .HasForeignKey("FolioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OM.MFPTracker.Data.Models.MutualFund", "Fund")
                        .WithMany("Transactions")
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Folio");

                    b.Navigation("Fund");
                });

            modelBuilder.Entity("OM.MFPTracker.Data.Models.MutualFund", b =>
                {
                    b.HasOne("OM.MFPTracker.Data.Models.Amc", "Amc")
                        .WithMany("MutualFunds")
                        .HasForeignKey("AmcId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OM.MFPTracker.Data.Models.MFCategory", "MFCategory")
                        .WithMany("MutualFunds")
                        .HasForeignKey("MFCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OM.MFPTracker.Data.Models.OperationalStatus", "OperationalStatus")
                        .WithMany()
                        .HasForeignKey("OperationalStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Amc");

                    b.Navigation("MFCategory");

                    b.Navigation("OperationalStatus");
                });

            modelBuilder.Entity("OM.MFPTracker.Data.Models.NavHistory", b =>
                {
                    b.HasOne("OM.MFPTracker.Data.Models.MutualFund", "MutualFund")
                        .WithMany("NavHistories")
                        .HasForeignKey("MutualFundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MutualFund");
                });

            modelBuilder.Entity("OM.MFPTracker.Data.Models.Amc", b =>
                {
                    b.Navigation("Folios");

                    b.Navigation("MutualFunds");
                });

            modelBuilder.Entity("OM.MFPTracker.Data.Models.Folio", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("OM.MFPTracker.Data.Models.FolioHolder", b =>
                {
                    b.Navigation("Folios");
                });

            modelBuilder.Entity("OM.MFPTracker.Data.Models.MFCategory", b =>
                {
                    b.Navigation("MutualFunds");
                });

            modelBuilder.Entity("OM.MFPTracker.Data.Models.MutualFund", b =>
                {
                    b.Navigation("NavHistories");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
