// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OM.MFPTracker.Data;

#nullable disable

namespace OM.MFPTracker.Data.Migrations
{
    [DbContext(typeof(MFPTrackerDbContext))]
    partial class MFPTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("OM.MFPTracker.Data.Models.Dummy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateTime>("InDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("updateDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("DummyTable", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "DK",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "RS",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("OM.MFPTracker.Data.Models.MFCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("TMFCategory", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "E-Multi Cap Mutual Funds"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "E-Flexi Cap Mutual Funds"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "E-Large & MidCap Mutual Funds"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "E-Large Cap Mutual Funds"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "E-Mid Cap Mutual Funds"
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "E-ELSS Mutual Funds"
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "E-Dividend Yield Mutual Funds"
                        },
                        new
                        {
                            Id = 8,
                            CategoryName = "E-Contra Mutual Funds"
                        },
                        new
                        {
                            Id = 9,
                            CategoryName = "E-Sectoral Mutual Funds"
                        },
                        new
                        {
                            Id = 10,
                            CategoryName = "E-Value Oriented Mutual Funds"
                        });
                });

            modelBuilder.Entity("OM.MFPTracker.Data.Models.MutualFund", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ISIN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateTime>("InDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("MFCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SchemeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("SchemeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ISIN")
                        .IsUnique();

                    b.HasIndex("MFCategoryId");

                    b.HasIndex("SchemeCode")
                        .IsUnique();

                    b.ToTable("TMutualFunds", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ISIN = "123AA",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MFCategoryId = 2,
                            SchemeCode = "B2C67",
                            SchemeName = "DK MF"
                        },
                        new
                        {
                            Id = 2,
                            ISIN = "12B4C",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MFCategoryId = 1,
                            SchemeCode = "AAC27",
                            SchemeName = "RK MF"
                        });
                });

            modelBuilder.Entity("OM.MFPTracker.Data.Models.NavHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("InDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("MutualFundId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NavDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NavValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MutualFundId", "NavDate")
                        .IsUnique();

                    b.ToTable("TNavHistory", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MutualFundId = 1,
                            NavDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NavValue = 125.4321m
                        },
                        new
                        {
                            Id = 2,
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MutualFundId = 1,
                            NavDate = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NavValue = 126.1000m
                        },
                        new
                        {
                            Id = 3,
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MutualFundId = 2,
                            NavDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NavValue = 98.7500m
                        },
                        new
                        {
                            Id = 4,
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MutualFundId = 2,
                            NavDate = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NavValue = 99.2500m
                        });
                });

            modelBuilder.Entity("OM.MFPTracker.Data.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("People", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(2002, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Rupam",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Shaw",
                            Signature = "RS",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1981, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Deepak",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Shaw",
                            Signature = "DK",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1974, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jagruti",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Shaw",
                            Signature = "JS",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(2001, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Divyam",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Shaw",
                            Signature = "DS",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Durga Prasad",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Shaw",
                            Signature = "DP",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Radha",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Shaw",
                            Signature = "RD",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("OM.MFPTracker.Data.Models.MutualFund", b =>
                {
                    b.HasOne("OM.MFPTracker.Data.Models.MFCategory", "MFCategory")
                        .WithMany("MutualFunds")
                        .HasForeignKey("MFCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MFCategory");
                });

            modelBuilder.Entity("OM.MFPTracker.Data.Models.NavHistory", b =>
                {
                    b.HasOne("OM.MFPTracker.Data.Models.MutualFund", "MutualFund")
                        .WithMany("NavHistories")
                        .HasForeignKey("MutualFundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MutualFund");
                });

            modelBuilder.Entity("OM.MFPTracker.Data.Models.MFCategory", b =>
                {
                    b.Navigation("MutualFunds");
                });

            modelBuilder.Entity("OM.MFPTracker.Data.Models.MutualFund", b =>
                {
                    b.Navigation("NavHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
